includes:
  - headers/data.yaml
  - headers/device.yaml
  # - headers/model.yaml
  # - headers/optimizer.yaml
  # - backbones/resnet12.yaml

# data_root: /data/fanzhichen/continual/cifar100
data_root: ./data/cifar10
image_size: 32


warmup: 3


save_path: ./
# data
init_cls_num: 2
inc_cls_num: 2
task_num: 5


batch_size: 128

init_epoch: 200  #100
epoch: 170  #100
 
device_ids: 0
n_gpu: 1
val_per_epoch: 10


optimizer:
  name: SGD
  kwargs:
    lr: 0.1
    momentum: 0.9
    weight_decay: 0.0005

lr_scheduler:
  name: CosineAnnealingLR
  kwargs:
    T_max: 100


backbone:
  name: cifar_resnet32
  kwargs:
    num_classes: 10
    args: 
      dataset: cifar10


buffer:
  name: LinearHerdingBuffer
  kwargs:
    buffer_size: 200
    batch_size: 64
    # strategy: herding     # random, equal_random, reservoir, herding

classifier:
  name: ICarl
  kwargs:
    num_class: 10
    feat_dim: 64
    init_cls_num: 2
    inc_cls_num: 2
    task_num: 5